apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: tk_phpadmin_img
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - /liveness.sh
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 2
---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - port: 5000
    name: phpmyadmin
    protocol: TCP
    targetPort: 5000
    nodePort: 5000