apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  selector:
    component: wordpress
  ports:
  - name: http
    protocol: TCP
    port: 5050
    targetPort: 5050
    nodePort: 5050
  type: NodePort
