apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: tk_wp_img
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
              - sh
              - /liveness.sh
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    name: wordpress
    protocol: TCP
    targetPort: 5050