apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debug
  name: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: debug
    spec:
      containers:
      - image: debug_pod
        imagePullPolicy: Never
        name: debug