apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - image: tk_ftps_img
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 20021
        livenessProbe:
          exec:
            command:
            - sh
            - /liveness.sh
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  ports:
  - name: data
    port: 20
    targetPort: 20
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps-pasv-min
    port: 30020
    protocol: TCP
    targetPort: 30020
  - name: ftps-pasv-max
    port: 30021
    protocol: TCP
    targetPort: 30021
  selector:
    app: ftps
  type: LoadBalancer